const CONFIG={SUPABASE_URL:"https://ecszjvqkuymmeweyghad.supabase.co",PUBLISHABLE_KEY:"sb_publishable_QGq_2DsvJjHLLI1XDMvxcQ_28TCcFnJ",FUNCTION_NAME:"parplan-api",BOT_USERNAME:"par_planer_bot"};
const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand()}
const COLORS=["#3b82f6","#8b5cf6","#f59e0b","#22a06b","#e05263","#14b8a6"];let state=null,viewMonth=new Date(),selectedDate=localISO(new Date()),simpleMode=null;let filters={tasks:"all",shopping:"all"};let busy=false;
function localISO(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function fmt(d){return new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"long",year:"numeric"}).format(new Date(d+"T12:00:00"))}
function me(){return state?.me?.id}function member(id){return state?.members.find(x=>x.id===id)}function color(m){return COLORS[(m?.color_index||0)%COLORS.length]}
function status(t){syncStatus.textContent=t}
async function api(action,data={}){const initData=tg?.initData||"";if(!initData)throw Error("Открой приложение внутри Telegram.");const r=await fetch(`${CONFIG.SUPABASE_URL}/functions/v1/${CONFIG.FUNCTION_NAME}`,{method:"POST",headers:{"Content-Type":"application/json",apikey:CONFIG.PUBLISHABLE_KEY,Authorization:"Bearer "+CONFIG.PUBLISHABLE_KEY},body:JSON.stringify({action,initData,data})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||"Ошибка соединения");return j}
async function load(silent=false){if(busy)return;busy=true;if(!silent)status("Синхронизация…");try{const r=await api("bootstrap",{startParam:tg?.initDataUnsafe?.start_param||null});state=r.state;renderAll();status("Синхронизировано")}catch(e){status(e.message||"Ошибка");if(!silent)alert(e.message)}finally{busy=false}}
async function act(action,data={}){try{status("Сохранение…");const r=await api(action,data);state=r.state;renderAll();status("Синхронизировано");return r}catch(e){status("Ошибка");alert(e.message);throw e}}
function chips(x){return x.participants.map(p=>{const m=member(p.user_id),s=p.status==="joined"?"участвует":p.status==="invited"?"приглашён":"отказался";return m?`<span class="chip ${p.status}">${esc(m.display_name)} · ${s}</span>`:""}).join("")}
function partButtons(kind,x){const p=x.participants.find(p=>p.user_id===me());if(!p)return"";const a=kind==="event"?"event_participation":kind==="task"?"task_participation":"shopping_participation";if(p.status==="joined")return `<button class="miniBtn decline" data-part="${a}|${x.id}|declined">Отказаться</button>`;if(p.status==="invited")return `<button class="miniBtn join" data-part="${a}|${x.id}|joined">✓ Присоединиться</button><button class="miniBtn decline" data-part="${a}|${x.id}|declined">✕ Отказаться</button>`;return `<button class="miniBtn join" data-part="${a}|${x.id}|joined">Присоединиться</button>`}
function renderCalendar(){monthTitle.textContent=new Intl.DateTimeFormat("ru-RU",{month:"long",year:"numeric"}).format(viewMonth);const y=viewMonth.getFullYear(),m=viewMonth.getMonth(),off=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate();calendar.innerHTML="";for(let i=0;i<42;i++){let d,dt,other=false;if(i<off){d=prev-off+i+1;dt=new Date(y,m-1,d);other=true}else if(i>=off+days){d=i-off-days+1;dt=new Date(y,m+1,d);other=true}else{d=i-off+1;dt=new Date(y,m,d)}const iso=localISO(dt),ev=state.events.filter(e=>e.event_date===iso),ids=[...new Set(ev.flatMap(e=>e.participants.filter(p=>p.status!=="declined").map(p=>p.user_id)))].slice(0,4);const b=document.createElement("button");b.className="day"+(other?" other":"")+(iso===selectedDate?" selected":"")+(iso===localISO(new Date())?" today":"");b.innerHTML=`<span>${d}</span><span class="dots">${ids.map(id=>`<i class="dot" style="background:${color(member(id))}"></i>`).join("")}</span>`;b.onclick=()=>{selectedDate=iso;viewMonth=new Date(dt.getFullYear(),dt.getMonth(),1);renderAll()};calendar.appendChild(b)}}
function renderEvents(){selectedDateTitle.textContent=fmt(selectedDate);const a=state.events.filter(e=>e.event_date===selectedDate).sort((a,b)=>a.start_time.localeCompare(b.start_time));eventsList.innerHTML=a.map(e=>`<div class="event"><div class="eventTime">${e.start_time.slice(0,5)}<br><span class="muted">${e.end_time.slice(0,5)}</span></div><div class="eventBody"><div class="eventTitle">${esc(e.title)}</div><div class="chips">${chips(e)}</div><div class="rowActions">${partButtons("event",e)}</div></div>${e.created_by===me()?`<button class="deleteBtn" data-del-event="${e.id}">×</button>`:""}</div>`).join("");eventsEmpty.style.display=a.length?"none":"block";let n=0;for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){const common=a[i].participants.filter(p=>p.status==="joined").some(p=>a[j].participants.some(q=>q.status==="joined"&&q.user_id===p.user_id));if(common&&a[i].start_time<a[j].end_time&&a[j].start_time<a[i].end_time)n++}if(n){overlapWarning.textContent=`⚠️ Есть пересекающиеся события: ${n}`;overlapWarning.classList.remove("hidden")}else overlapWarning.classList.add("hidden")}
function renderMembers(){memberCount.textContent=state.members.length+" участн.";membersList.innerHTML=state.members.map(m=>`<div class="memberRow"><div class="memberAvatar" style="background:${color(m)}">${esc((m.display_name||"?")[0])}</div><div><strong>${esc(m.display_name)}</strong><div class="muted">${m.id===me()?"Вы":m.role==="owner"?"Создатель":"Участник"}</div></div></div>`).join("")}
function filtered(type){const f=filters[type];return state[type].filter(x=>{const ids=x.participants.filter(p=>p.status==="joined").map(p=>p.user_id);return f==="all"||f==="mine"&&ids.includes(me())||f==="other"&&ids.length&&!ids.includes(me())||f==="common"&&ids.length>1})}
function renderRows(type,list,empty,filterBox){filterBox.innerHTML=[["all","Все"],["mine","Моё"],["other","Других"],["common","Общее"]].map(([v,t])=>`<button class="filterBtn ${filters[type]===v?"active":""}" data-filter="${type}|${v}">${t}</button>`).join("");const a=filtered(type);list.innerHTML=a.map(x=>`<div class="rowItem ${x.is_completed?"done":""}"><input type="checkbox" ${x.is_completed?"checked":""} data-toggle="${type}|${x.id}"><div class="rowText"><div>${esc(x.title)}</div><div class="rowMeta">${chips(x)}</div><div class="rowActions">${partButtons(type==="tasks"?"task":"shopping",x)}</div></div>${x.created_by===me()?`<button class="deleteBtn" data-del="${type}|${x.id}">×</button>`:""}</div>`).join("");empty.style.display=a.length?"none":"block"}
function bind(){document.querySelectorAll("[data-part]").forEach(b=>b.onclick=()=>{const[a,id,status]=b.dataset.part.split("|");act(a,{id,status})});document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{const[t,f]=b.dataset.filter.split("|");filters[t]=f;renderAll()});document.querySelectorAll("[data-toggle]").forEach(b=>b.onchange=()=>{const[t,id]=b.dataset.toggle.split("|");act(t==="tasks"?"toggle_task":"toggle_shopping",{id,is_completed:b.checked})});document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{const[t,id]=b.dataset.del.split("|");act(t==="tasks"?"delete_task":"delete_shopping",{id})});document.querySelectorAll("[data-del-event]").forEach(b=>b.onclick=()=>act("delete_event",{id:b.dataset.delEvent}))}
function renderAll(){if(!state)return;spaceTitle.textContent=state.space.name;renderCalendar();renderEvents();renderMembers();renderRows("tasks",tasksList,tasksEmpty,tasksFilters);renderRows("shopping",shoppingList,shoppingEmpty,shoppingFilters);bind()}
prevMonth.onclick=()=>{viewMonth=new Date(viewMonth.getFullYear(),viewMonth.getMonth()-1,1);renderCalendar()};nextMonth.onclick=()=>{viewMonth=new Date(viewMonth.getFullYear(),viewMonth.getMonth()+1,1);renderCalendar()};document.querySelectorAll(".navItem").forEach(b=>b.onclick=()=>{document.querySelectorAll(".navItem").forEach(x=>x.classList.remove("active"));document.querySelectorAll("#calendarView,#tasksView,#shoppingView,#peopleView").forEach(x=>x.classList.add("hidden"));b.classList.add("active");document.getElementById(b.dataset.view).classList.remove("hidden")});
addEventBtn.onclick=()=>{eventTitle.value="";eventDate.value=selectedDate;eventStart.value="";eventEnd.value="";eventMembers.innerHTML=state.members.map(m=>`<label class="checkItem"><input type="checkbox" value="${m.id}" ${m.id===me()?"checked":""}>${esc(m.display_name)}</label>`).join("");eventDialog.showModal()};eventForm.onsubmit=async e=>{e.preventDefault();const participantIds=[...document.querySelectorAll("#eventMembers input:checked")].map(x=>x.value);if(!participantIds.length)return alert("Выбери участника.");if(eventEnd.value<=eventStart.value)return alert("Проверь время.");await act("create_event",{title:eventTitle.value.trim(),event_date:eventDate.value,start_time:eventStart.value,end_time:eventEnd.value,participantIds});selectedDate=eventDate.value;eventDialog.close()};
function openSimple(mode,title){simpleMode=mode;simpleTitle.textContent=title;simpleInput.value="";simpleMembers.innerHTML=state.members.map(m=>`<label class="checkItem"><input type="checkbox" value="${m.id}" ${m.id===me()?"checked":""}>${esc(m.display_name)}</label>`).join("");simpleDialog.showModal()}addTaskBtn.onclick=()=>openSimple("tasks","Новое дело");addShoppingBtn.onclick=()=>openSimple("shopping","Новая покупка");simpleForm.onsubmit=async e=>{e.preventDefault();const participantIds=[...document.querySelectorAll("#simpleMembers input:checked")].map(x=>x.value);if(!participantIds.length)return alert("Выбери участника.");await act(simpleMode==="tasks"?"create_task":"create_shopping",{title:simpleInput.value.trim(),participantIds});simpleDialog.close()};
inviteBtn.onclick=async()=>{const r=await act("create_invite");const link=`https://t.me/${CONFIG.BOT_USERNAME}?startapp=${r.token}`;const share="https://t.me/share/url?url="+encodeURIComponent(link)+"&text="+encodeURIComponent("Присоединяйся к моему пространству в parplan");tg?.openTelegramLink?tg.openTelegramLink(share):navigator.clipboard.writeText(link)};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());settingsBtn.onclick=async()=>{const n=prompt("Название пространства:",state.space.name);if(n?.trim())await act("rename_space",{name:n.trim()})};setInterval(()=>load(true),8000);load();
